# https://taskfile.dev

version: '3'

silent: true

tasks:
  up:
    dir: ./docker
    cmds:
      - docker compose up --wait
  rebuild:
    dir: ./docker
    cmds:
      - docker compose down -v
      - docker compose up --build --wait
  down:
    dir: ./docker
    cmds:
      - docker compose down
  reset:
    dir: ./docker
    cmds:
      - docker compose down -v
  db:
    dir: ./docker
    cmds:
      - docker compose exec db mysql -u root -ppassword app
  log:
    dir: ./docker
    cmds:
      - cmd: docker compose logs -f app
        ignore_error: true
