version: "3.8"

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./..:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app #TODO: アプリ名に変える
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./../mysql/init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
      - ./../mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    expose:
      - 3306

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysql:
